#! /usr/bin/env python3

import sys
import os

site_path = os.path.dirname(os.path.abspath(sys.argv[0]))
dist_path = os.path.join(site_path, 'dist')
sys.path.append(os.path.join(site_path, 'lib'))

import iknsite

iknsite.Site(site_path, dist_path).build()
