#! /usr/bin/env python3

import sys
import os

site_path = os.path.dirname(os.path.dirname(os.path.abspath(sys.argv[0])))
src_path = os.path.join(site_path, 'src')
dist_path = os.path.join(site_path, 'dist')
sys.path.append(os.path.join(src_path, 'lib'))

import iknsite

iknsite.Site(src_path, dist_path).build()
