version: "3.8"
services:
  ikn:
    image: iknorguk/ikn:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ikn-apache-md:/usr/local/apache2/md
      - ${IKN_DOWNLOAD_PATH:-/opt/ikn/download}:/usr/local/apache2/htdocs/ikn.org.uk/download
      - ${IKN_FILESHARE_PATH:-/opt/ikn/fileshare}:/usr/local/apache2/htdocs/stuff.ikn.org.uk/fileshare
    environment:
      IKN_TLS_DISABLED: ${IKN_TLS_DISABLED}

volumes:
  ikn-apache-md:
