version: "3.8"
services:
  ikn:
    image: iknorguk/ikn:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ikn-apache-md:/usr/local/apache2/md
    environment:
      IKN_TLS_DISABLED: ${IKN_TLS_DISABLED}

volumes:
  ikn-apache-md:
